### ISSUE TITLE
Unit Test Cases

### ISSUE THREAD

**Issue by rohts-patil** [SforAiDl/decepticonlp#12]
Any project should have unit cases and should work as CI so that any other contributor should not break things that were previously working.

**Comment by rajaswa** [comment]
@rohts-patil  We have some character transforms implemented, we can start with unit tests for that maybe.
As far as CI is concerned, what do you propose, and are you willing to take it up?

**Comment by rohts-patil** [comment]
We can set a Github Action for python package. I have set it on my fork.

Check it out https://github.com/rohts-patil/decepticonlp/actions/runs/100153783

**Comment by rohts-patil** [comment]
Let me know if you guys are ok with this, I will raise a PR.

**Comment by Sharad24** [comment]
Sounds good to me. Github Actions (The Free plan) is only upto 2000 minutes though. 

But I dont think we're ever going to go past that. Althought, If you're planning on doing other things with Github Actions (Pre-commit runs e.g. Black formatting, packaging, etc) it might be a good idea to do builds and docs with Travis CI (its free)

**Comment by rohts-patil** [comment]
Closing this issue as I have added the simple example test for delete. 
Others can use it as a template and or go through pytest tutorials.
