### ISSUE TITLE
Implement Metrics

### ISSUE THREAD

**Issue by someshsingh22** [SforAiDl/decepticonlp#15]
Implement standard metrics from [this paper](https://arxiv.org/pdf/1812.05271.pdf)

1. Edit Distance (Levenshtein)
2. Jaccard Similarity Coefficient (n-char grams)
3. Euclidean Distance
4. Semantic Similarity

**Comment by parantak** [comment]
> Implement standard metrics from [this paper](https://arxiv.org/pdf/1812.05271.pdf)
> 
> 1. Edit Distance (Levenshtein)
> 2. Jaccard Similarity Coefficient (n-char grams)
> 3. Euclidean Distance
> 4. Semantic Similarity

They used to Universal Sentence Encoder when checking for semantic similarity, I believe we could add options for the use of different embeddings and even tf-idf.
