### ISSUE TITLE
Add support of Substitute-C (Sub-C)

### ISSUE THREAD

**Issue by rohts-patil** [SforAiDl/decepticonlp#28]
Substitute-C (Sub-C): Replace characters with visually similar characters (e.g., replacing “o” with “0”, “l” with “1”, “a” with “@”) or adjacent characters in the keyboard (e.g., replacing “m” with “n”).

We can use a pre-compiled dictionary from https://github.com/codebox/homoglyph/blob/master/raw_data/chars.txt

**Comment by someshsingh22** [comment]
@shashank-m You can have a look

**Comment by rajaswa** [comment]
Typo perturbation has already been implemented in #19

**Comment by someshsingh22** [comment]
Typo perturbation is different

**Comment by rajaswa** [comment]
Agreed. @someshsingh22 
Was referring to the issue's request to merge typo with Sub-C

**Comment by shashank-m** [comment]
yeah i'll start working on this now
