### ISSUE TITLE
similarity between n-gram vectors (Metric)

### ISSUE THREAD

**Issue by parantak** [SforAiDl/decepticonlp#30]
I believe one of us could implement the following:
1. Extract n-grams from both sentences.
2. Construct respective vectors for both sentences, where a '1' or a '0' would indicate the presence or non-presence of an n-gram. 
3. Calculate cosine similarity.

There's literature where people have used this metric, I can't seem to find as of now. I will update it later.
Note: could also use all (1,2...k) grams to capture more context, comes as the cost of more computation time.

**Comment by someshsingh22** [comment]
Yeah please update it, also this is very similar to Jaccard distance anyways Jaccard consists of unigrams, maybe we can pass a window size. unigrams anyways only work for words and not strings, nice suggestion!
