### ISSUE TITLE
Implement keyword Extractors

### ISSUE THREAD

**Issue by someshsingh22** [SforAiDl/decepticonlp#32]
Implement Temporal Score, Tailed Temporal Score, Combined Temporal Score 
[from here](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8424632)
and Semantic Similarity
[from here](https://arxiv.org/pdf/1812.05271.pdf)

in extractor/extractor.py
also add the unit test for it

**Comment by Sharad24** [comment]
What help do you need here? Maybe I could help.

**Comment by someshsingh22** [comment]
It's Just implementation that has a high priority because it is crucial for the next stage, we have to implement the Temporal score, TTS, and Temporal Combined Scores as given in the links

**Comment by rajaswa** [comment]
In case this is blocking further development, you can select top-k random words (random default extractor) from the sample to apply transforms (where k is a user-defined argument)
Once the extractors are in place, we can add them one by one to the list of available extractors along with the default random extractor

**Comment by rajaswa** [comment]
It'll also be better if we follow an object-oriented approach for this from the very beginning

**Comment by someshsingh22** [comment]
Ok so I am adding a random function (In fact we can also use this for a baseline, how well random works in comparison to when we use extractor"

**Comment by rohts-patil** [comment]
Is there any help required on this issue?
If not can we please remove the help wanted tag? @someshsingh22

**Comment by someshsingh22** [comment]
Yes, the syntax is pretty clear now

**Comment by abheesht17** [comment]
I'll implement Semantic Similarity, @rajaswa, @someshsingh22.

**Comment by blackrosedragon2** [comment]
Could I implement temporal score?

**Comment by someshsingh22** [comment]
Yes, absolutely; Once we complete it, We will near a milestone in our repo
