### ISSUE TITLE
OOP implementation of Bugger

### ISSUE THREAD

**Issue by someshsingh22** [SforAiDl/decepticonlp#33]
Design and Implement an OOP Structure for our Bugger, which will take a dataset, get queried by the user and generate bugged sentences.

For imp word extractor use a temporary random selector for the time being.

Refer to slack for reference

**Comment by Sharad24** [comment]
Great! If you're working on this issue, think about where this ideally fits in the whole pipeline.

As for a design choice, ideally you'd like to to cater to someone who's an expert and a noob but not keep it very messy. (Best example for this is Matplotlib)

**Comment by rajaswa** [comment]
I'll be writing an example high-level design code in the README today. That shall give us a good idea about the low-level implementations @someshsingh22

**Comment by rajaswa** [comment]
Also, we need to be very specific with transform names so that the user can distinguish between them easily
Ex: swap ---> character_swap; delete ---> character_delete etc

**Comment by rohts-patil** [comment]
I can start on this.

**Comment by someshsingh22** [comment]
Yes, that would be nice, so you are talking about the design right ?

**Comment by rohts-patil** [comment]
I was thinking about design and code both. @someshsingh22 
Also, this would be a huge refactor, so we need to come up with a strategy where no one's work gets interrupted or have huge merge conflicts later.
The strategy being code freeze for a day.

**Comment by someshsingh22** [comment]
Exactly, we have to start working asap, we need a word extractor for the actual implementation, but for the time being we can assume it to be some function

**Comment by rajaswa** [comment]
You can start working on this immediately @rohts-patil  . I'll freeze all the PRs for perturb.py for the time being. While you are at it, can you handle the ignore=True condition in a more efficient way?

**Comment by rajaswa** [comment]
Issue resolved in #39
