### ISSUE TITLE
Implementation of Contractions (Paraphrasing)

### ISSUE THREAD

**Issue by abheesht17** [SforAiDl/decepticonlp#34]
Suppose we have a string with two words **"how is"**. We can replace it with its contraction **"how's"**. This can be done for multiple cases like:
**he will**: **he'll**
**he had**: **he'd** 
and so on and so forth.
This paper does it for Question Answering/Machine Translation: https://www.aclweb.org/anthology/P18-1079.pdf. 

I'm sure there are many other papers which have examples of replacing words with their respective contractions.

As @rajaswa mentioned, this isn't exactly a character-level perturbation and comes under the domain of paraphrasing. So, we can have multiple other examples of paraphrasing and implement those.

**Comment by rajaswa** [comment]
We can have a new module for this 
```
decepticonlp/transforms/paraphrase.py
```

Will you be willing to take this up? @abheesht17

**Comment by abheesht17** [comment]
Yep

**Comment by rajaswa** [comment]
Assigned to @abheesht17 .
Please make sure to cover corner cases and corresponding test cases too

**Comment by rajaswa** [comment]
Resolved in #50
