### ISSUE TITLE
Implementation of Repeating Characters

### ISSUE THREAD

**Issue by blackrosedragon2** [SforAiDl/decepticonlp#37]
Consider a word like "sales" and we add an extra "a"  it becomes "saales". This feature can be added as a enhancement to the current code. Please refer to the following paper for more details : https://arxiv.org/pdf/1905.11268.pdf  (check the figure on page 4 for quick reference)

**Comment by rajaswa** [comment]
This can be extended to add any random character also. Need to discuss more about the functionality of the proposed perturbation

**Comment by blackrosedragon2** [comment]
You're right, lets make it for random characters. I was thinking [A-Za-z]* should get appended to the input string, to select the positions that should get appended i can create a list of a random size consisting of random indices where the random character would get appended.

**Comment by rajaswa** [comment]
Sounds good. You can start working on a function for now. The corresponding PR will be accepted once #33 is dealt with

**Comment by blackrosedragon2** [comment]
I'll get right on it

**Comment by someshsingh22** [comment]
A reminder, this is very similar to insert_space in perturb, so we there is no sense in adding another function, just add an argument instead
default is ' '
there should be an option "alphabet" which means [a-zA-Z]

**Comment by blackrosedragon2** [comment]
Alright, ill make the changes on that function specifically

**Comment by blackrosedragon2** [comment]
What if there are multiple perturbations, at multiple indices?

**Comment by someshsingh22** [comment]
@blackrosedragon2, The code structure has been changed a lot, so before you implement just make sure you are doing it to in accordance with the latest format, because this is what we will probably use ahead. refer to this -> https://github.com/SforAiDl/decepticonlp/commit/de1571a13cd8811bf7d093766dd0da5f2fac5b0a
