### ISSUE TITLE
OOP implementation of metrics.py

### ISSUE THREAD

**Issue by rajaswa** [SforAiDl/decepticonlp#49]
Similar to perturbations.py, we need an OOP implementation for metrics.py , with an abstract method .calculate() maybe?

**Comment by someshsingh22** [comment]
I think .distance() would be more specific and elaborate
Jaccard Distance, Edit distance, Euclidean distance are the metrics till now

**Comment by rohts-patil** [comment]
I think the `calculate()` method will be appropriate.

For example, class name is `EuclideanDistanceMetric` and use it as `EuclideanDistanceMetric.calculate(vector from, vector to)`
 @someshsingh22 

Also, is there any possibility that there would be metrics added in the future that are not distance-based?

**Comment by someshsingh22** [comment]
This is basically how different two strings are so it will always remain the distance, other metrics for string comparisons are also called distance. .calculate() alone did not look correct however EucledianDistance.calculate(x,y) looks pretty accurate

**Comment by rajaswa** [comment]
Lets stick to .calclate() for the time being

**Comment by parantak** [comment]
I think as we implement more metrics, we could perhaps split them into subcategories like edit-based(Levenshtein, etc.), token-based (Jaccard, etc.), vector-based, etc.

**Comment by parantak** [comment]
OOP implementation. If you want a different structure, let me know.
